-- MySQL Script generated by MySQL Workbench
-- 11/01/16 21:16:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MARCA` (
  `idMarca` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VEICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VEICULO` (
  `idVeiculo` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `MARCA_idMarca` INT NOT NULL,
  PRIMARY KEY (`idVeiculo`),
  INDEX `fk_VEICULO_MARCA_idx` (`MARCA_idMarca` ASC),
  CONSTRAINT `fk_VEICULO_MARCA`
    FOREIGN KEY (`MARCA_idMarca`)
    REFERENCES `mydb`.`MARCA` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPOREVISAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPOREVISAO` (
  `idTipoRevisao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoRevisao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ATENDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ATENDENTE` (
  `idAtendente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idAtendente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REVISAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REVISAO` (
  `idRevisao` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `data` DATE NOT NULL,
  `valor` FLOAT NOT NULL,
  `tempoPrevisto` FLOAT NOT NULL,
  `CLIENTE_idCliente` INT NOT NULL,
  `VEICULO_idVeiculo` INT NOT NULL,
  `ATENDENTE_idAtendente` INT NOT NULL,
  `TIPOREVISAO_idTipoRevisao` INT NOT NULL,
  PRIMARY KEY (`idRevisao`, `CLIENTE_idCliente`, `VEICULO_idVeiculo`, `ATENDENTE_idAtendente`, `TIPOREVISAO_idTipoRevisao`),
  INDEX `fk_REVISAO_TIPOREVISAO1_idx` (`TIPOREVISAO_idTipoRevisao` ASC),
  INDEX `fk_REVISAO_ATENDENTE1_idx` (`ATENDENTE_idAtendente` ASC),
  INDEX `fk_REVISAO_VEICULO1_idx` (`VEICULO_idVeiculo` ASC),
  INDEX `fk_REVISAO_CLIENTE1_idx` (`CLIENTE_idCliente` ASC),
  CONSTRAINT `fk_REVISAO_TIPOREVISAO1`
    FOREIGN KEY (`TIPOREVISAO_idTipoRevisao`)
    REFERENCES `mydb`.`TIPOREVISAO` (`idTipoRevisao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVISAO_ATENDENTE1`
    FOREIGN KEY (`ATENDENTE_idAtendente`)
    REFERENCES `mydb`.`ATENDENTE` (`idAtendente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVISAO_VEICULO1`
    FOREIGN KEY (`VEICULO_idVeiculo`)
    REFERENCES `mydb`.`VEICULO` (`idVeiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REVISAO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCliente`)
    REFERENCES `mydb`.`CLIENTE` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
