algoritmo "Programa 2"
// Função :
var
Num1, Dobro, Triplo, Quadrado, DivDois: real
inicio
escreva ("Digite um numero: ")
leia (Num1)

Dobro <- Num1 * 2
Triplo <- Num1 * 3
Quadrado <- Num1 * Num1
DivDois <- Num1 / 2

escreval ("O dobro de ",Num1," é: ",Dobro)
escreval ("O triplo de ",Num1," é: ",Triplo)
escreval ("O quadrado de ",Num1," é: ",Quadrado)
escreval (Num1," divido por 2 é: ",DivDois)

fimalgoritmo
