-- MySQL Script generated by MySQL Workbench
-- 10/18/16 20:41:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIO` (
  `matricula` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `cpf` INT(11) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDOR` (
  `codFornecedor` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`codFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `codProduto` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `FORNECEDOR_codFornecedor` VARCHAR(11) NOT NULL,
  `valor` FLOAT NOT NULL,
  `PRODUTOcol` VARCHAR(45) NULL,
  PRIMARY KEY (`codProduto`),
  INDEX `fk_PRODUTO_FORNECEDOR1_idx` (`FORNECEDOR_codFornecedor` ASC),
  CONSTRAINT `fk_PRODUTO_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_codFornecedor`)
    REFERENCES `mydb`.`FORNECEDOR` (`codFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDA` (
  `codVenda` INT NOT NULL AUTO_INCREMENT,
  `descricaoVenda` VARCHAR(45) NOT NULL,
  `qtdProduto` INT(11) NOT NULL,
  `dataVenda` DATE NOT NULL,
  `FUNCIONARIO_matricula` VARCHAR(45) NOT NULL,
  `PRODUTO_codProduto` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`codVenda`),
  INDEX `fk_VENDA_FUNCIONARIO_idx` (`FUNCIONARIO_matricula` ASC),
  INDEX `fk_VENDA_PRODUTO1_idx` (`PRODUTO_codProduto` ASC),
  CONSTRAINT `fk_VENDA_FUNCIONARIO`
    FOREIGN KEY (`FUNCIONARIO_matricula`)
    REFERENCES `mydb`.`FUNCIONARIO` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codProduto`)
    REFERENCES `mydb`.`PRODUTO` (`codProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
